language: rust
sudo: false

cache: cargo

rust:
  - 1.35.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

env: RUST_BACKTRACE=1
before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/cargo-generate || cargo install --vers "^0.2" cargo-generate)
  - cargo install-update -a
  - rustup target add wasm32-unknown-unknown

script:
  - cargo doc
  - wasm-pack build
  - wasm-pack test --chrome --firefox --headless
