language: rust
sudo: false

cache: cargo

rust:
  - 1.35.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo doc
  - wasm-pack build
  - wasm-pack test --chrome --firefox --headless
