[package]
name = "typed-array"
version = "0.1.0"
authors = ["Thomas den Hollander <denhollander.thomas@gmail.com>"]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
err-derive = "0.1.5"
